# This workflows starts scraping Routescanner each day at 06:00 UTC, and opens a PR to merge the gathered data

name: Parsing
on:
  schedule:
    - cron: "0 */3 * * *"
  push:
    paths:
     - ".github/workflows/parsing-git.yml"
     - "parsing-git.py"
  workflow_dispatch:

jobs:
  parsing:
    runs-on: ubuntu-latest
    timeout-minutes: 240
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v6
      with:
        python-version: "3.13"
        cache: 'pip'
    - run: pip install -r requirements.txt
    - run: python parsing.py
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update data ${{ github.event.repository.updated_at}}"
