# This workflows starts scraping Routescanner each day at 06:00 UTC, and opens a PR to merge the gathered data

name: Parsing
on:
  schedule:
    - cron: "0,6,12,18,24,30,36,42,48,54 * * * *"
  push:
    paths:
     - ".github/workflows/parsing.yml"
     - "parsing.py"
  workflow_dispatch:

jobs:
  routescanner:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'
    - run: pip install -r requirements.txt
    - run: python parsing.py
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update data ${{ github.event.repository.updated_at}}"
